controllers:
    resource: ../src/Controller/
    type: attribute

# index:
#     path: /home
#     controller: App\Controller\HomeController::index
# contact:
#     path: /contact
#     controller: App\Controller\HomeController::contact